---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v1
  labels:
    app: portfolio-backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-backend
      version: v1
  template:
    metadata:
      labels:
        app: portfolio-backend
        version: v1
    spec:
      containers:
        - name: backend
          image: dockergc00/portfolio-backend:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v2
  labels:
    app: portfolio-backend
    version: v2
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-backend
      version: v2
  template:
    metadata:
      labels:
        app: portfolio-backend
        version: v2
    spec:
      containers:
        - name: backend
          image: dockergc00/portfolio-backend:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-v3
  labels:
    app: portfolio-backend
    version: v3
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio-backend
      version: v3
  template:
    metadata:
      labels:
        app: portfolio-backend
        version: v3
    spec:
      containers:
        - name: backend
          image: dockergc00/portfolio-backend:v3
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
