# helm/portfolio-frontend/values.yaml
replicaCount: 1

image:
  repository: "dockergc00/portfolio-frontend"   # <- updated repository
  tag: "v1"                                     # <- added tag
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

backend:
  host: portfolio-backend
  port: 5000
  path: /
