apiVersion: v1
kind: Service
metadata:
  name: portfolio-frontend
  labels:
    app: portfolio-frontend
spec:
  type: ClusterIP
  selector:
    app: portfolio-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
