apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portfolio-frontend-vs
spec:
  hosts:
    - "*"
  gateways:
    - portfolio-frontend-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: portfolio-frontend
            port:
              number: 3000
