apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portfolio-backend-vs
spec:
  hosts:
    - portfolio-backend
  http:
    - route:
        - destination:
            host: portfolio-backend
            subset: v1
            port:
              number: 5000
          weight: 25
        - destination:
            host: portfolio-backend
            subset: v2
            port:
              number: 5000
          weight: 25
        - destination:
            host: portfolio-backend
            subset: v3
            port:
              number: 5000
          weight: 50
