version: "3.9"

services:

  backend-v1:
    build: ./backend-v1
    container_name: backend-v1
    ports:
      - "5001:5000"
    networks:
      - appnet

  backend-v2:
    build: ./backend-v2
    container_name: backend-v2
    ports:
      - "5002:5000"
    networks:
      - appnet

  backend-v3:
    build: ./backend-v3
    container_name: backend-v3
    ports:
      - "5003:5000"
    networks:
      - appnet

  backend-gateway:
    image: nginx:latest
    container_name: backend-gateway
    depends_on:
      - backend-v1
      - backend-v2
      - backend-v3
    ports:
      - "5000:5000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  frontend:
    build: ./frontend
    container_name: frontend
    depends_on:
      - backend-gateway
    ports:
      - "3000:3000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
