############################################
# FRONTEND SERVICE
############################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.frontend.name }}
  labels:
    app: {{ .Values.frontend.name }}
spec:
  selector:
    app: {{ .Values.frontend.name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: {{ .Values.frontend.port }}

---

############################################
# BACKEND SERVICE (shared for all versions)
############################################
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.backend.name }}
  labels:
    app: {{ .Values.backend.name }}
spec:
  selector:
    app: {{ .Values.backend.name }}
  ports:
    - name: http
      protocol: TCP
      port: 5000
      targetPort: {{ .Values.backend.port }}
