{{- if .Values.istio.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: portfolio-virtualservice
spec:
  hosts:
    - "*"
  gateways:
    - portfolio-gateway
  http:

    # Backend routes
    - match:
        - uri:
            prefix: /api
      route:
        {{- range .Values.backend.versions }}
        - destination:
            host: {{ $.Values.backend.name }}
            subset: {{ .name }}
          weight: {{ .weight }}
        {{- end }}

    # Frontend route
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: portfolio-frontend
            port:
              number: 80
{{- end }}
