# Default values for portfolio. 
# These values will be used in the Helm chart templates.

replicaCount: 1
frontend:
  name: portfolio-frontend
  image: dockergc00/gc-devops-portfolio-frontend
  tag: b8b46dd
  port: 3000
backend:
  name: portfolio-backend
  port: 5000
  versions:
    - name: v1
      image: dockergc00/gc-devops-portfolio-backend-v1
      tag: v1
      weight: 70
    - name: v2
      image: dockergc00/gc-devops-portfolio-backend-v2
      tag: v1
      weight: 20
    - name: v3
      image: dockergc00/gc-devops-portfolio-backend-v3
      tag: v1
      weight: 10
  v1:
    tag: b8b46dd
  v2:
    tag: b8b46dd
  v3:
    tag: b8b46dd
istio:
  enabled: true # Enable Istio integration important for traffic management
  gatewayHost: "*"
