# Default values for portfolio.

replicaCount: 1
frontend:
  name: portfolio-frontend
  image: dockergc00/gc-devops-portfolio-frontend
  tag: 2f4c620
  port: 3000
backend:
  name: portfolio-backend
  port: 5000
  versions:
    - name: v1
      image: dockergc00/gc-devops-portfolio-backend-v1
      tag: 7753c0b
      weight: 70
    - name: v2
      image: dockergc00/gc-devops-portfolio-backend-v2
      tag: 7753c0b
      weight: 20
    - name: v3
      image: dockergc00/gc-devops-portfolio-backend-v3
      tag: 7753c0b
      weight: 10
  v1:
    tag: 2f4c620
  v2:
    tag: 2f4c620
  v3:
    tag: 2f4c620
istio:
  enabled: true
  gatewayHost: "*"
