replicaCount: 1

imageRegistry: dockergc00

frontend:
  name: portfolio-frontend
  image: dockergc00/gc-devops-portfolio-frontend
  tag: v2
  port: 3000

backend:
  v1:
    name: portfolio-backend-v1
    image: dockergc00/gc-devops-portfolio-backend-v1
    tag: v1
    weight: 70

  v2:
    name: portfolio-backend-v2
    image: dockergc00/gc-devops-portfolio-backend-v2
    tag: v1
    weight: 20

  v3:
    name: portfolio-backend-v3
    image: dockergc00/gc-devops-portfolio-backend-v3
    tag: v1
    weight: 10

istio:
  enabled: true
  gatewayHost: "*"
