name: Frontend CI Pipeline

on:
  push:
    branches:
      - dev
      - stage
      - main
    paths:
      - "phase2-portfolio/app/frontend/**"
      - ".github/workflows/frontend-ci.yaml"

permissions:
  contents: read
  packages: write

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Docker Tag based on branch
        id: vars
        run: |
          if [[ "${GITHUB_REF_NAME}" == "dev" ]]; then
            echo "TAG=dev-$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          elif [[ "${GITHUB_REF_NAME}" == "stage" ]]; then
            echo "TAG=stage-$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT
          else
            echo "TAG=latest" >> $GITHUB_OUTPUT
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      ###############################################
      # FRONTEND BUILD & PUSH
      ###############################################
      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:${{ steps.vars.outputs.TAG }} \
          -f phase2-portfolio/app/frontend/Dockerfile \
          phase2-portfolio/app/frontend

      - name: Push frontend image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-frontend:${{ steps.vars.outputs.TAG }}
