name: Backend CI Pipeline

on:
  push:
    paths:
      - "phase2-portfolio/app/backend-v1/**"
      - "phase2-portfolio/app/backend-v2/**"
      - "phase2-portfolio/app/backend-v3/**"
      - ".github/workflows/backend-ci.yaml"
    branches:
      - dev
      - stage
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract short SHA
        id: vars
        run: echo "TAG=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Build & Push backend-v1
      - name: Build backend-v1
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend-v1:${{ steps.vars.outputs.TAG }} \
            -f phase2-portfolio/app/backend-v1/Dockerfile \
            phase2-portfolio/app/backend-v1

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend-v1:${{ steps.vars.outputs.TAG }}

      # Build & Push backend-v2
      - name: Build backend-v2
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend-v2:${{ steps.vars.outputs.TAG }} \
            -f phase2-portfolio/app/backend-v2/Dockerfile \
            phase2-portfolio/app/backend-v2

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend-v2:${{ steps.vars.outputs.TAG }}

      # Build & Push backend-v3
      - name: Build backend-v3
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend-v3:${{ steps.vars.outputs.TAG }} \
            -f phase2-portfolio/app/backend-v3/Dockerfile \
            phase2-portfolio/app/backend-v3

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/portfolio-backend-v3:${{ steps.vars.outputs.TAG }}
