name: CD - Prod Deployment

on:
  push:
    branches:
      - main
    paths:
      - 'phase2-portfolio/k8s/overlays/prod/**'
      - '.github/workflows/cd-prod.yaml'

jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set git identity
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions"

      # Update backend v1
      - name: Update backend-v1 image tag
        run: |
          sed -i "s|image: .*portfolio-backend-v1:.*|image: dockergc00/portfolio-backend-v1:prod|g" \
            phase2-portfolio/k8s/base/backend/deployment.yaml

      # Update backend v2
      - name: Update backend-v2 image tag
        run: |
          sed -i "s|image: .*portfolio-backend-v2:.*|image: dockergc00/portfolio-backend-v2:prod|g" \
            phase2-portfolio/k8s/base/backend/deployment.yaml

      # Update backend v3
      - name: Update backend-v3 image tag
        run: |
          sed -i "s|image: .*portfolio-backend-v3:.*|image: dockergc00/portfolio-backend-v3:prod|g" \
            phase2-portfolio/k8s/base/backend/deployment.yaml

      # Update Frontend
      - name: Update frontend image tag
        run: |
          sed -i "s|image: .*portfolio-frontend:.*|image: dockergc00/portfolio-frontend:prod|g" \
            phase2-portfolio/k8s/base/frontend/deployment.yaml

      - name: Commit & Push
        run: |
          git add .
          git commit -m "CD: Update prod images to stable tags"
          git push origin main
